version: '2'
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - gomodguard
    - noinlineerr
    - nlreturn
    - varnamelen
    - wsl
    - wsl_v5
  settings:
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - goconst
          - lll
        path: _test\.go$
      - linters:
          - lll
        path: internal/layout/ansiflags\.go
      - linters:
          - lll
        path: internal/layout/comnt\.go
      - linters:
          - lll
        path: internal/layout/datatype\.go
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
