# golangci-lint run
#
# Fixes
# gci write ./..
# gofumpt -w .
#

linters:
  enable-all: true
  disable:
    # Deprecated
    - interfacer
    - scopelint
    - golint
    - maligned
    - deadcode
    - ifshort
    - nosnakecase
    - varcheck
    - exhaustivestruct
    - structcheck

    # Opinionated
    - depguard # unwanted, as it requires a list of packages
    - exhaustruct # requires too much boilerplate
    - lll # too much of a hassle
    - nlreturn # opinionated
    - tagalign # requires correctly aligned structs
    - paralleltest # too much of a hassle for no gain
    - varnamelen # annoying
    - wsl # whitespace linter, aggressive and opinionated

linters-settings:
  cyclop:
    # the maximal code complexity to report
    max-complexity: 15
