version: '2'
linters:
  default: all
  disable:
    - exhaustruct_v5
    - noinlineerr
    - nlreturn
    - varnamelen
    - wsl_v5
    # retired
    - wsl
    - exhaustruct
    - gomodguard
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - linters:
          - goconst
          - lll
        path: _test\.go$
      - linters:
          - lll
        path: internal/layout/ansiflags\.go
      - linters:
          - lll
        path: internal/layout/comnt\.go
      - linters:
          - lll
        path: internal/layout/datatype\.go
  settings:
    cyclop:
      max-complexity: 15
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - 'golang.org/x/text'
            - 'github.com/nalgeon/be'
            - 'github.com/bengarrett/sauce'
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
