version: "2"
linters:
  default: all
  disable:
    - depguard
    - exhaustruct
    - lll
    - nlreturn
    - paralleltest
    - tagalign
    - varnamelen
    - wsl
  settings:
    cyclop:
      max-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
