name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      version:
        description: 'Go version to build with'
        required: false
        default: '1.17'
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ github.event.inputs.version }

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...